
create table if not exists user
(
  id         bigint generated by default as identity primary key,
  username   varchar(42) not null,
  first_name varchar(20) not null,
  last_name  varchar(20) not null,
  email      varchar(50) not null,
  password   varchar(60) not null,
  created_on  TIMESTAMP WITH TIME ZONE not null
);
